spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/mylog}
    username: ${DB_USERNAME:mylog}
    password: ${DB_PASSWORD:mylog_local_password}

mylog:
  security:
    jwt:
      signing-key-base64: ${JWT_SIGNING_KEY_BASE64:bXlsb2ctbG9jYWwtZGV2LWtleS1kb250LXVzZS1pbi1wcm9k}

management:
  endpoint:
    health:
      show-details: always
