spring:
  jpa:
    show-sql: false
  data:
    redis:
      repositories:
        enabled: false

mylog:
  open-api:
    enabled: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: false
